language: python

dist: trusty

cache: pip

matrix:
  include:
  - python: "2.7"
    env: NUMPY_VERSION=1.7.1
  - python: "3.6"
    env: NUMPY_VERSION=1.7.1
  - python: "3.6"
    env: NUMPY_VERSION=1.12.1

install: pip install numpy==$NUMPY_VERSION

script:
  - python -c 'import numpy as np; print("numpy:", np.__version__)'
  - py.test
